//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelproDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikli
    {
        public Artikli()
        {
            this.Stavke_narudzbe = new HashSet<Stavke_narudzbe>();
        }
    
        public int ID_artikla { get; set; }
        public string Naziv_artikla { get; set; }
        public decimal Cijena_artikla { get; set; }
        public decimal Dostupna_kolicina { get; set; }
        public string Opis_artikla { get; set; }
    
        public virtual ICollection<Stavke_narudzbe> Stavke_narudzbe { get; set; }
    }
}
