//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelproDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        public Korisnici()
        {
            this.Lista_zelja = new HashSet<Lista_zelja>();
            this.Narudzbenice = new HashSet<Narudzbenice>();
        }
    
        public int ID_korisnika { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Korisnicko_ime { get; set; }
        public string Lozinka { get; set; }
        public string E_mail { get; set; }
        public string Broj_telefona { get; set; }
        public int Uloga { get; set; }
    
        public virtual Uloge Uloge { get; set; }
        public virtual ICollection<Lista_zelja> Lista_zelja { get; set; }
        public virtual ICollection<Narudzbenice> Narudzbenice { get; set; }
    }
}
