//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelproDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavke_narudzbe
    {
        public int ID_narudzbenice { get; set; }
        public int ID_artikla { get; set; }
        public decimal Kolicina { get; set; }
    
        public virtual Artikli Artikli { get; set; }
        public virtual Narudzbenice Narudzbenice { get; set; }
    }
}
