//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelproDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uloge
    {
        public Uloge()
        {
            this.Korisnici = new HashSet<Korisnici>();
        }
    
        public int ID_Uloge { get; set; }
        public string Naziv_uloge { get; set; }
    
        public virtual ICollection<Korisnici> Korisnici { get; set; }
    }
}
