//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Velpro_za_korisnika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dobavljaci
    {
        public int ID_dobavljaca { get; set; }
        public string Naziv_dobavljaca { get; set; }
        public string E_mail_dobavljaca { get; set; }
        public int ID_narudzbenice { get; set; }
    
        public virtual Narudzbenice Narudzbenice { get; set; }
    }
}
