//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Velpro_za_korisnika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbenice
    {
        public Narudzbenice()
        {
            this.Dobavljacis = new HashSet<Dobavljaci>();
            this.Stavke_narudzbe = new HashSet<Stavke_narudzbe>();
        }
    
        public int ID_narudzbenice { get; set; }
        public string Adresa_dostave { get; set; }
        public System.DateTime Datum_i_vrijeme { get; set; }
        public int ID_korisnika { get; set; }
        public bool Aktivna { get; set; }
    
        public virtual ICollection<Dobavljaci> Dobavljacis { get; set; }
        public virtual Korisnici Korisnici { get; set; }
        public virtual ICollection<Stavke_narudzbe> Stavke_narudzbe { get; set; }
    }
}
